---
name: output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: output github and environment context
        run: |
          echo "${{ toJson(github) }}"
          echo "${{ toJson(env) }}"
